name: auto updater (PR)

on:
  pull_request:

  workflow_dispatch:

jobs:
  auto-updater:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: christianvuerings/add-labels@v1
      with:
        labels: |
          auto update
          test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
