name: auto updater (push)

on:
  push:
    branches: 
      - "main"

  workflow_dispatch:

jobs:
  auto-updater:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: run arbitrary script
      run: |
        python3 ./.github/scripts/hello.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update data
